### ISSUE TITLE
[TypeError: object is not a function]

### ISSUE THREAD

**Issue by tiagojco** [monaca/monaca-cli#74]
When issuing 

> monaca preview

i get the above mentioned output.
installed via sudo npm install -g monaca

Environment:
ubuntu 14.04
node 0.10.25
npm 1.3.10
monaca 2.1.3

I don't really know how to provide a more detailed "stacktrace". Maybe if someone can guide me.

**Comment by frandiox** [comment]
@tiagojco Can you try with a more updated version of Node? Perhaps some dependencies don't work with 0.10.25. I think 0.12.x was fine, but 4+ works for sure.

**Comment by tiagojco** [comment]
0.10.25 is the default node version in the ubuntu 10.04 package manager
after installing node 4 via nvm it worked

thanks
